-- Vetted event associations for Vietnamese history thesis project.
-- Resets event_relations so prior experimental/full-coverage relation seed data does not remain in runtime APIs.

START TRANSACTION;

DELETE FROM event_relations;

CREATE TEMPORARY TABLE event_relation_seed (
    source_event_id VARCHAR(160) NOT NULL,
    target_event_id VARCHAR(160) NOT NULL,
    association_type ENUM('predecessor', 'successor', 'related') NOT NULL,
    relation_type ENUM('related', 'predecessor', 'successor', 'same_topic', 'same_location') NOT NULL,
    sort_order INT NOT NULL DEFAULT 0
) ENGINE=Memory;

INSERT INTO event_relation_seed
    (source_event_id, target_event_id, association_type, relation_type, sort_order)
VALUES
('bac-thanh-duoc-lap', 'xoa-bo-bac-thanh-chia-thanh-18-tinh', 'successor', 'successor', 1),
('bai-bo-che-do-tem-phieu-o-viet-nam', 'giai-doan-khoi-dau-cong-cuoc-doi-moi-1986-1995', 'predecessor', 'predecessor', 1),
('bai-bo-che-do-tem-phieu-o-viet-nam', 'dai-hoi-dai-bieu-toan-quoc-lan-thu-vii-cua-dang-cong-san-viet-nam', 'successor', 'successor', 1),
('ban-hanh-chinh-sach-han-dien', 'phat-hanh-tien-giay-thong-bao-hoi-sao', 'related', 'same_topic', 1),
('ban-hanh-chinh-sach-han-dien', 'ho-quy-ly-doi-do-thanh-hoa', 'related', 'same_topic', 2),
('ban-hanh-chinh-sach-han-no', 'ho-quy-ly-lap-trieu-ho', 'related', 'same_topic', 1),
('ban-hanh-chinh-sach-loc-dien-quan-dien', 'dat-them-thua-tuyen-quang-nam', 'predecessor', 'predecessor', 1),
('ban-hanh-chinh-sach-loc-dien-quan-dien', 'ban-hanh-quoc-trieu-hinh-luat', 'successor', 'successor', 1),
('ban-hanh-nghi-quyet-36-nq-tw-ve-chien-luoc-phat-trien-kinh-te-bien', 'viet-nam-thong-qua-luat-bien-viet-nam', 'related', 'same_topic', 1),
('ban-hanh-quoc-trieu-hinh-luat', 'ban-hanh-chinh-sach-loc-dien-quan-dien', 'predecessor', 'predecessor', 1),
('ban-hanh-quoc-trieu-hinh-luat', 'le-thanh-tong-dung-bia-tien-si-van-mieu', 'successor', 'successor', 1),
('bo-chinh-tri-ban-hanh-chi-thi-05-ct-tw-ve-day-manh-hoc-tap-va-lam-theo-tu-tuong-dao-duc-phong-cach-ho-chi-minh', 'bo-chinh-tri-ban-hanh-chi-thi-06-ct-tw-ve-cuoc-van-dong-hoc-tap-va-lam-theo-tam-guong-dao-duc-ho-chi-minh', 'predecessor', 'predecessor', 1),
('bo-chinh-tri-ban-hanh-chi-thi-06-ct-tw-ve-cuoc-van-dong-hoc-tap-va-lam-theo-tam-guong-dao-duc-ho-chi-minh', 'bo-chinh-tri-ban-hanh-chi-thi-05-ct-tw-ve-day-manh-hoc-tap-va-lam-theo-tu-tuong-dao-duc-phong-cach-ho-chi-minh', 'successor', 'successor', 1),
('bru-nay-tuyen-bo-ranh-gioi-them-luc-dia', 'bru-nay-tuyen-bo-vung-dac-quyen-kinh-te', 'related', 'same_topic', 1),
('bru-nay-tuyen-bo-vung-dac-quyen-kinh-te', 'bru-nay-tuyen-bo-ranh-gioi-them-luc-dia', 'related', 'same_topic', 1),
('cac-chien-dich-tien-cong-quan-doi-viet-nam-1950-1953', 'chien-dich-bien-gioi-thu-dong-1950', 'predecessor', 'predecessor', 1),
('cac-chien-dich-tien-cong-quan-doi-viet-nam-1950-1953', 'ke-hoach-na-va-1953', 'successor', 'successor', 1),
('cac-dia-phuong-cuoi-cung-gianh-chinh-quyen', 'khoi-nghia-gianh-chinh-quyen-sai-gon', 'predecessor', 'predecessor', 1),
('cac-dia-phuong-cuoi-cung-gianh-chinh-quyen', 'tong-khoi-nghia-gianh-chinh-quyen', 'successor', 'successor', 1),
('cac-tinh-gianh-chinh-quyen-som-nhat', 'dai-hoi-quoc-dan-tan-trao', 'predecessor', 'predecessor', 1),
('cac-tinh-gianh-chinh-quyen-som-nhat', 'khoi-nghia-gianh-chinh-quyen-ha-noi', 'successor', 'successor', 1),
('cach-mang-thang-tam-nam-1945', 'chi-thi-thanh-lap-doi-viet-nam-tuyen-truyen-giai-phong-quan', 'predecessor', 'predecessor', 1),
('cach-mang-thang-tam-nam-1945', 'thanh-lap-mat-tran-viet-nam-doc-lap-dong-minh-viet-minh', 'predecessor', 'predecessor', 2),
('cai-cach-ho-quy-ly-trieu-ho', 'khung-hoang-cuoi-trieu-tran', 'predecessor', 'predecessor', 1),
('cai-cach-ho-quy-ly-trieu-ho', 'phat-hanh-tien-giay-thong-bao-hoi-sao', 'related', 'same_topic', 1),
('cai-cach-ho-quy-ly-trieu-ho', 'nha-minh-xam-luoc-dai-ngu', 'successor', 'successor', 1),
('cai-to-hanh-chinh-dia-phuong-12-thua-tuyen', 'le-thanh-tong-dua-luc-bo-thanh-co-quan-quyen-luc', 'predecessor', 'predecessor', 1),
('cai-to-hanh-chinh-dia-phuong-12-thua-tuyen', 'cai-to-he-thong-quan-doi-le-thanh-tong', 'successor', 'successor', 1),
('cai-to-he-thong-quan-doi-le-thanh-tong', 'cai-to-hanh-chinh-dia-phuong-12-thua-tuyen', 'predecessor', 'predecessor', 1),
('cai-to-he-thong-quan-doi-le-thanh-tong', 'dat-them-thua-tuyen-quang-nam', 'successor', 'successor', 1),
('cao-trao-khang-nhat-cuu-nuoc', 'nhat-ban-tuyen-bo-dau-hang-dong-minh', 'successor', 'successor', 1),
('chi-thi-thanh-lap-doi-viet-nam-tuyen-truyen-giai-phong-quan', 'ho-chi-minh-tro-ve-nuoc-1944', 'predecessor', 'predecessor', 1),
('chi-thi-thanh-lap-doi-viet-nam-tuyen-truyen-giai-phong-quan', 'cach-mang-thang-tam-nam-1945', 'successor', 'successor', 1),
('chien-dau-cac-do-thi-phia-bac-vi-tuyen-16-1946-1947', 'khang-chien-toan-quoc-chong-thuc-dan-phap-bung-no', 'predecessor', 'predecessor', 1),
('chien-dau-cac-do-thi-phia-bac-vi-tuyen-16-1946-1947', 'chien-dich-viet-bac-thu-dong-1947', 'successor', 'successor', 1),
('chien-dich-bien-gioi-thu-dong-1950', 'chien-dich-viet-bac-thu-dong-1947', 'predecessor', 'predecessor', 1),
('chien-dich-bien-gioi-thu-dong-1950', 'cac-chien-dich-tien-cong-quan-doi-viet-nam-1950-1953', 'successor', 'successor', 1),
('chien-dich-dien-bien-phu-1954', 'cuoc-tien-cong-chien-luoc-dong-xuan-1953-1954', 'predecessor', 'predecessor', 1),
('chien-dich-dien-bien-phu-1954', 'khang-chien-thang-loi', 'related', 'related', 1),
('chien-dich-dien-bien-phu-1954', 'hoi-nghi-gio-ne-vo-ve-dong-duong', 'successor', 'successor', 1),
('chien-dich-giai-phong-sai-gon-gia-dinh-chien-dich-ho-chi-minh', 'giai-phong-da-nang', 'predecessor', 'predecessor', 1),
('chien-dich-giai-phong-sai-gon-gia-dinh-chien-dich-ho-chi-minh', 'hoan-toan-giai-phong-mien-nam-viet-nam', 'successor', 'successor', 1),
('chien-dich-tay-nguyen-1975', 'chien-thang-duong-14-phuoc-long', 'predecessor', 'predecessor', 1),
('chien-dich-tay-nguyen-1975', 'giai-phong-hue-va-thua-thien', 'successor', 'successor', 1),
('chien-dich-viet-bac-thu-dong-1947', 'chien-dau-cac-do-thi-phia-bac-vi-tuyen-16-1946-1947', 'predecessor', 'predecessor', 1),
('chien-dich-viet-bac-thu-dong-1947', 'chien-dich-bien-gioi-thu-dong-1950', 'successor', 'successor', 1),
('chien-si-hai-quan-nhan-dan-viet-nam-hi-sinh-bao-ve-gac-ma-co-lin-len-dao', 'trung-quoc-danh-chiem-da-vanh-khan', 'related', 'same_topic', 1),
('chien-si-hai-quan-nhan-dan-viet-nam-hi-sinh-bao-ve-gac-ma-co-lin-len-dao', 'trung-quoc-danh-chiem-dao-gac-ma-len-dao-chu-thap-va-mot-so-dao-khac-truong-sa', 'related', 'same_topic', 2),
('chien-thang-ap-bac', 'thanh-lap-quan-giai-phong-mien-nam', 'predecessor', 'predecessor', 1),
('chien-thang-ap-bac', 'chien-thang-van-tuong', 'successor', 'successor', 1),
('chien-thang-bach-dang-938', 'khoi-nghia-khuc-thua-du', 'predecessor', 'predecessor', 1),
('chien-thang-bach-dang-938', 'ngo-quyen-xung-vuong-co-loa', 'successor', 'successor', 1),
('chien-thang-duong-14-phuoc-long', 'hoi-nghi-ban-chap-hanh-trung-uong-dang-lan-thu-21', 'predecessor', 'predecessor', 1),
('chien-thang-duong-14-phuoc-long', 'chien-dich-tay-nguyen-1975', 'successor', 'successor', 1),
('chien-thang-van-tuong', 'chien-thang-ap-bac', 'predecessor', 'predecessor', 1),
('chien-thang-van-tuong', 'tong-tien-cong-va-noi-day-xuan-mau-than-1968', 'successor', 'successor', 1),
('chien-tranh-pha-hoai-mien-bac-lan-thu-hai', 'cuoc-tien-cong-chien-luoc-nam-1972', 'predecessor', 'predecessor', 1),
('chien-tranh-pha-hoai-mien-bac-lan-thu-hai', 'chien-tranh-pha-hoai-mien-bac-lan-thu-nhat', 'related', 'same_topic', 1),
('chien-tranh-pha-hoai-mien-bac-lan-thu-hai', 'ki-ket-hiep-dinh-pa-ri-ve-cham-dut-chien-tranh-lap-lai-hoa-binh-o-viet-nam', 'successor', 'successor', 1),
('chien-tranh-pha-hoai-mien-bac-lan-thu-nhat', 'chien-tranh-pha-hoai-mien-bac-lan-thu-hai', 'related', 'same_topic', 1),
('cuoc-tien-cong-chien-luoc-dong-xuan-1953-1954', 'ke-hoach-na-va-1953', 'predecessor', 'predecessor', 1),
('cuoc-tien-cong-chien-luoc-dong-xuan-1953-1954', 'chien-dich-dien-bien-phu-1954', 'successor', 'successor', 1),
('cuoc-tien-cong-chien-luoc-nam-1972', 'thanh-lap-chinh-phu-cach-mang-lam-thoi-cong-hoa-mien-nam-viet-nam', 'predecessor', 'predecessor', 1),
('cuoc-tien-cong-chien-luoc-nam-1972', 'chien-tranh-pha-hoai-mien-bac-lan-thu-hai', 'successor', 'successor', 1),
('dai-hoi-dai-bieu-lan-thu-ii-cua-dang-lao-dong-viet-nam', 'dai-hoi-dai-bieu-lan-thu-ii-dang-cong-san-dong-duong-1951', 'related', 'same_topic', 1),
('dai-hoi-dai-bieu-lan-thu-ii-dang-cong-san-dong-duong-1951', 'dai-hoi-dai-bieu-lan-thu-ii-cua-dang-lao-dong-viet-nam', 'related', 'same_topic', 1),
('dai-hoi-dai-bieu-toan-quoc-lan-thu-iii-cua-dang-lao-dong-viet-nam', 'dai-hoi-dai-bieu-toan-quoc-lan-thu-iii-dang-lao-dong-viet-nam', 'related', 'same_topic', 1),
('dai-hoi-dai-bieu-toan-quoc-lan-thu-iii-dang-lao-dong-viet-nam', 'dai-hoi-dai-bieu-toan-quoc-lan-thu-iii-cua-dang-lao-dong-viet-nam', 'related', 'same_topic', 1),
('dai-hoi-dai-bieu-toan-quoc-lan-thu-vi-cua-dang-cong-san-viet-nam', 'dai-hoi-dai-bieu-toan-quoc-lan-thu-vii-cua-dang-cong-san-viet-nam', 'related', 'same_topic', 1),
('dai-hoi-dai-bieu-toan-quoc-lan-thu-vi-cua-dang-cong-san-viet-nam', 'giai-doan-khoi-dau-cong-cuoc-doi-moi-1986-1995', 'successor', 'successor', 1),
('dai-hoi-dai-bieu-toan-quoc-lan-thu-vii-cua-dang-cong-san-viet-nam', 'bai-bo-che-do-tem-phieu-o-viet-nam', 'predecessor', 'predecessor', 1),
('dai-hoi-dai-bieu-toan-quoc-lan-thu-vii-cua-dang-cong-san-viet-nam', 'dai-hoi-dai-bieu-toan-quoc-lan-thu-vi-cua-dang-cong-san-viet-nam', 'related', 'same_topic', 1),
('dai-hoi-dai-bieu-toan-quoc-lan-thu-vii-cua-dang-cong-san-viet-nam', 'dai-hoi-dai-bieu-toan-quoc-lan-thu-viii-cua-dang-cong-san-viet-nam', 'related', 'same_topic', 2),
('dai-hoi-dai-bieu-toan-quoc-lan-thu-vii-cua-dang-cong-san-viet-nam', 'viet-nam-binh-thuong-hoa-quan-he-trung-quoc', 'successor', 'successor', 1),
('dai-hoi-dai-bieu-toan-quoc-lan-thu-viii-cua-dang-cong-san-viet-nam', 'viet-nam-gia-nhap-asean', 'predecessor', 'predecessor', 1),
('dai-hoi-dai-bieu-toan-quoc-lan-thu-viii-cua-dang-cong-san-viet-nam', 'dai-hoi-dai-bieu-toan-quoc-lan-thu-vii-cua-dang-cong-san-viet-nam', 'related', 'same_topic', 1),
('dai-hoi-dai-bieu-toan-quoc-lan-thu-viii-cua-dang-cong-san-viet-nam', 'dai-hoi-dai-bieu-toan-quoc-lan-thu-x-cua-dang-cong-san-viet-nam', 'related', 'same_topic', 2),
('dai-hoi-dai-bieu-toan-quoc-lan-thu-viii-cua-dang-cong-san-viet-nam', 'giai-doan-day-manh-cong-nghiep-hoa-hien-dai-hoa-hoi-nhap-kinh-te-quoc-te-1996-2006', 'successor', 'successor', 1),
('dai-hoi-dai-bieu-toan-quoc-lan-thu-x-cua-dang-cong-san-viet-nam', 'giai-doan-day-manh-cong-nghiep-hoa-hien-dai-hoa-hoi-nhap-kinh-te-quoc-te-1996-2006', 'predecessor', 'predecessor', 1),
('dai-hoi-dai-bieu-toan-quoc-lan-thu-x-cua-dang-cong-san-viet-nam', 'dai-hoi-dai-bieu-toan-quoc-lan-thu-viii-cua-dang-cong-san-viet-nam', 'related', 'same_topic', 1),
('dai-hoi-dai-bieu-toan-quoc-lan-thu-x-cua-dang-cong-san-viet-nam', 'giai-doan-tiep-tuc-day-manh-cong-nghiep-hoa-hien-dai-hoa-hoi-nhap-quoc-te-sau-rong-2006-nay', 'successor', 'successor', 1),
('dai-hoi-quoc-dan-tan-trao', 'hoi-nghi-toan-quoc-cua-dang-cong-san-dong-duong-1945', 'predecessor', 'predecessor', 1),
('dai-hoi-quoc-dan-tan-trao', 'cac-tinh-gianh-chinh-quyen-som-nhat', 'successor', 'successor', 1),
('dat-them-thua-tuyen-quang-nam', 'cai-to-he-thong-quan-doi-le-thanh-tong', 'predecessor', 'predecessor', 1),
('dat-them-thua-tuyen-quang-nam', 'ban-hanh-chinh-sach-loc-dien-quan-dien', 'successor', 'successor', 1),
('dinh-tien-le-dong-do-hoa-lu', 'ngo-quyen-xung-vuong-co-loa', 'predecessor', 'predecessor', 1),
('dinh-tien-le-dong-do-hoa-lu', 'khang-chien-chong-quan-tong-981', 'successor', 'successor', 1),
('do-dac-cam-moc-chu-quyen-hoang-sa-pham-huu-nhat', 'thanh-lap-va-hoat-dong-doi-dan-binh-hoang-sa-bac-hai', 'predecessor', 'predecessor', 1),
('doi-cac-doanh-quang-binh-quang-tri-quang-nam-thanh-tran', 'doi-dinh-quang-duc-thanh-phu-thua-thien', 'predecessor', 'predecessor', 1),
('doi-cac-doanh-quang-binh-quang-tri-quang-nam-thanh-tran', 'lap-noi-cac-thay-the-van-thu-phong', 'successor', 'successor', 1),
('doi-dinh-quang-duc-thanh-phu-thua-thien', 'doi-thi-thu-vien-thanh-van-thu-phong', 'predecessor', 'predecessor', 1),
('doi-dinh-quang-duc-thanh-phu-thua-thien', 'doi-cac-doanh-quang-binh-quang-tri-quang-nam-thanh-tran', 'successor', 'successor', 1),
('doi-do-ly-cong-uan', 'ly-thai-to-doi-do-thang-long', 'related', 'same_topic', 1),
('doi-do-ly-cong-uan', 'ly-thanh-tong-dung-van-mieu', 'successor', 'successor', 1),
('doi-thi-thu-vien-thanh-van-thu-phong', 'minh-mang-len-ngoi-vua', 'predecessor', 'predecessor', 1),
('doi-thi-thu-vien-thanh-van-thu-phong', 'doi-dinh-quang-duc-thanh-phu-thua-thien', 'successor', 'successor', 1),
('gia-dinh-thanh-duoc-lap', 'xoa-bo-gia-dinh-thanh-chia-thanh-12-tinh', 'successor', 'successor', 1),
('giai-doan-day-manh-cong-nghiep-hoa-hien-dai-hoa-hoi-nhap-kinh-te-quoc-te-1996-2006', 'dai-hoi-dai-bieu-toan-quoc-lan-thu-viii-cua-dang-cong-san-viet-nam', 'predecessor', 'predecessor', 1),
('giai-doan-day-manh-cong-nghiep-hoa-hien-dai-hoa-hoi-nhap-kinh-te-quoc-te-1996-2006', 'dai-hoi-dai-bieu-toan-quoc-lan-thu-x-cua-dang-cong-san-viet-nam', 'successor', 'successor', 1),
('giai-doan-khang-chien-chong-my-1954-1960', 'giai-doan-khang-chien-chong-my-1961-1965', 'successor', 'successor', 1),
('giai-doan-khang-chien-chong-my-1961-1965', 'giai-doan-khang-chien-chong-my-1954-1960', 'predecessor', 'predecessor', 1),
('giai-doan-khang-chien-chong-my-1961-1965', 'giai-doan-khang-chien-chong-my-1965-1968', 'successor', 'successor', 1),
('giai-doan-khang-chien-chong-my-1965-1968', 'giai-doan-khang-chien-chong-my-1961-1965', 'predecessor', 'predecessor', 1),
('giai-doan-khang-chien-chong-my-1965-1968', 'giai-doan-khang-chien-chong-my-1969-1973', 'successor', 'successor', 1),
('giai-doan-khang-chien-chong-my-1969-1973', 'giai-doan-khang-chien-chong-my-1965-1968', 'predecessor', 'predecessor', 1),
('giai-doan-khang-chien-chong-my-1969-1973', 'giai-doan-khang-chien-chong-my-1973-1975', 'successor', 'successor', 1),
('giai-doan-khang-chien-chong-my-1973-1975', 'giai-doan-khang-chien-chong-my-1969-1973', 'predecessor', 'predecessor', 1),
('giai-doan-khoi-dau-cong-cuoc-doi-moi-1986-1995', 'dai-hoi-dai-bieu-toan-quoc-lan-thu-vi-cua-dang-cong-san-viet-nam', 'predecessor', 'predecessor', 1),
('giai-doan-khoi-dau-cong-cuoc-doi-moi-1986-1995', 'bai-bo-che-do-tem-phieu-o-viet-nam', 'successor', 'successor', 1),
('giai-doan-tiep-tuc-day-manh-cong-nghiep-hoa-hien-dai-hoa-hoi-nhap-quoc-te-sau-rong-2006-nay', 'dai-hoi-dai-bieu-toan-quoc-lan-thu-x-cua-dang-cong-san-viet-nam', 'predecessor', 'predecessor', 1),
('giai-phong-da-nang', 'giai-phong-hue-va-thua-thien', 'predecessor', 'predecessor', 1),
('giai-phong-da-nang', 'chien-dich-giai-phong-sai-gon-gia-dinh-chien-dich-ho-chi-minh', 'successor', 'successor', 1),
('giai-phong-hue-va-thua-thien', 'chien-dich-tay-nguyen-1975', 'predecessor', 'predecessor', 1),
('giai-phong-hue-va-thua-thien', 'giai-phong-da-nang', 'successor', 'successor', 1),
('giai-phong-thi-xa-thai-nguyen', 'tong-khoi-nghia-gianh-chinh-quyen', 'related', 'related', 1),
('hien-phap-viet-nam-dan-chu-cong-hoa-1946', 'ho-chi-minh-duoc-bau-chu-tich-nuoc-1946', 'predecessor', 'predecessor', 1),
('hiep-uoc-hac-mang', 'phap-chiem-bac-ki-lan-2', 'predecessor', 'predecessor', 1),
('hiep-uoc-hac-mang', 'hiep-uoc-pa-to-not', 'successor', 'successor', 1),
('hiep-uoc-hoa-phap-1946', 'ho-chi-minh-ki-hiep-dinh-so-bo-voi-g-xanh-to-ni', 'successor', 'successor', 1),
('hiep-uoc-pa-to-not', 'hiep-uoc-hac-mang', 'predecessor', 'predecessor', 1),
('hiep-uoc-pa-to-not', 'phong-trao-can-vuong', 'successor', 'successor', 1),
('hinh-thanh-phat-trien-van-minh-cham-pa', 'khoi-nghia-khu-lien-lap-nuoc-lam-ap', 'related', 'same_topic', 1),
('hinh-thanh-phat-trien-van-minh-phu-nam', 'phu-nam-tro-thanh-vuong-quoc-hung-manh', 'related', 'same_topic', 1),
('ho-chi-minh-cong-bo-tuyen-ngon-doc-lap', 'tong-khoi-nghia-gianh-chinh-quyen', 'predecessor', 'predecessor', 1),
('ho-chi-minh-di-trung-quoc-phoi-hop-chong-nhat', 'thanh-lap-tieu-doi-du-kich-thoat-li-dau-tien-o-cao-bang', 'predecessor', 'predecessor', 1),
('ho-chi-minh-di-trung-quoc-phoi-hop-chong-nhat', 'ho-chi-minh-sang-trung-quoc-1942', 'related', 'same_topic', 1),
('ho-chi-minh-di-trung-quoc-phoi-hop-chong-nhat', 'ho-chi-minh-tro-ve-nuoc-1944', 'successor', 'successor', 1),
('ho-chi-minh-duoc-bau-chu-tich-nuoc-1946', 'ho-chi-minh-gui-loi-keu-goi-quoc-dan-di-bo-phieu', 'predecessor', 'predecessor', 1),
('ho-chi-minh-duoc-bau-chu-tich-nuoc-1946', 'hien-phap-viet-nam-dan-chu-cong-hoa-1946', 'successor', 'successor', 1),
('ho-chi-minh-gui-loi-keu-goi-quoc-dan-di-bo-phieu', 'ho-chi-minh-duoc-bau-chu-tich-nuoc-1946', 'successor', 'successor', 1),
('ho-chi-minh-ki-hiep-dinh-so-bo-voi-g-xanh-to-ni', 'hiep-uoc-hoa-phap-1946', 'predecessor', 'predecessor', 1),
('ho-chi-minh-ki-hiep-dinh-so-bo-voi-g-xanh-to-ni', 'ho-chi-minh-sang-phap-van-dong-ngoai-giao-va-ki-tam-uoc', 'successor', 'successor', 1),
('ho-chi-minh-mo-lop-dao-tao-can-bo-tai-quang-chau-trung-quoc', 'nguyen-ai-quoc-den-quang-chau-1924', 'related', 'related', 1),
('ho-chi-minh-ra-loi-keu-goi-toan-quoc-khang-chien', 'khang-chien-toan-quoc-chong-thuc-dan-phap-bung-no', 'related', 'same_topic', 1),
('ho-chi-minh-sang-phap-van-dong-ngoai-giao-va-ki-tam-uoc', 'ho-chi-minh-ki-hiep-dinh-so-bo-voi-g-xanh-to-ni', 'predecessor', 'predecessor', 1),
('ho-chi-minh-sang-phap-van-dong-ngoai-giao-va-ki-tam-uoc', 'ki-tam-uoc-viet-phap', 'successor', 'successor', 1),
('ho-chi-minh-sang-trung-quoc-1942', 'ho-chi-minh-di-trung-quoc-phoi-hop-chong-nhat', 'related', 'same_topic', 1),
('ho-chi-minh-tro-ve-nuoc-1944', 'ho-chi-minh-di-trung-quoc-phoi-hop-chong-nhat', 'predecessor', 'predecessor', 1),
('ho-chi-minh-tro-ve-nuoc-1944', 'chi-thi-thanh-lap-doi-viet-nam-tuyen-truyen-giai-phong-quan', 'successor', 'successor', 1),
('ho-khuc-to-chuc-lai-lang-xa-the-ki-x', 'khoi-nghia-khuc-thua-du', 'related', 'related', 1),
('ho-quy-ly-doi-do-thanh-hoa', 'ban-hanh-chinh-sach-han-dien', 'related', 'same_topic', 1),
('ho-quy-ly-doi-do-thanh-hoa', 'ho-quy-ly-lap-trieu-ho', 'related', 'same_topic', 2),
('ho-quy-ly-lap-trieu-ho', 'ho-quy-ly-doi-do-thanh-hoa', 'related', 'same_topic', 1),
('ho-quy-ly-lap-trieu-ho', 'ban-hanh-chinh-sach-han-no', 'related', 'same_topic', 2),
('hoan-toan-giai-phong-mien-nam-viet-nam', 'chien-dich-giai-phong-sai-gon-gia-dinh-chien-dich-ho-chi-minh', 'predecessor', 'predecessor', 1),
('hoan-toan-giai-phong-mien-nam-viet-nam', 'mit-tinh-chao-mung-uy-ban-quan-quan-sai-gon-1975', 'successor', 'successor', 1),
('hoan-toan-giai-phong-mien-nam-viet-nam', 'thuc-hien-thong-nhat-dat-nuoc-viet-nam', 'successor', 'successor', 2),
('hoat-dong-doi-ngoai-phan-boi-chau', 'phong-trao-dong-du', 'related', 'same_topic', 1),
('hoat-dong-doi-ngoai-phan-boi-chau', 'phan-boi-chau-sang-nhat-ban-1905', 'related', 'same_topic', 2),
('hoat-dong-doi-ngoai-phan-chau-trinh', 'phan-chau-trinh-sang-phap-1911', 'related', 'same_topic', 1),
('hoi-nghi-ban-chap-hanh-trung-uong-dang-lan-thu-21', 'ki-ket-hiep-dinh-pa-ri-ve-cham-dut-chien-tranh-lap-lai-hoa-binh-o-viet-nam', 'predecessor', 'predecessor', 1),
('hoi-nghi-ban-chap-hanh-trung-uong-dang-lan-thu-21', 'chien-thang-duong-14-phuoc-long', 'successor', 'successor', 1),
('hoi-nghi-ban-chap-hanh-trung-uong-lan-thu-15-dang-lao-dong-viet-nam', 'my-thay-chan-phap-dung-chinh-quyen-ngo-dinh-diem', 'predecessor', 'predecessor', 1),
('hoi-nghi-ban-chap-hanh-trung-uong-lan-thu-15-dang-lao-dong-viet-nam', 'phong-trao-dong-khoi', 'successor', 'successor', 1),
('hoi-nghi-binh-than', 'khang-chien-chong-quan-mong-co-1258', 'predecessor', 'predecessor', 1),
('hoi-nghi-binh-than', 'hoi-nghi-dien-hong', 'successor', 'successor', 1),
('hoi-nghi-dien-hong', 'hoi-nghi-binh-than', 'predecessor', 'predecessor', 1),
('hoi-nghi-dien-hong', 'khang-chien-chong-quan-nguyen-1285', 'successor', 'successor', 1),
('hoi-nghi-gio-ne-vo-ve-dong-duong', 'chien-dich-dien-bien-phu-1954', 'predecessor', 'predecessor', 1),
('hoi-nghi-gio-ne-vo-ve-dong-duong', 'ky-ket-hiep-dinh-go-ne-vo-1954', 'successor', 'successor', 1),
('hoi-nghi-lan-thu-8-ban-chap-hanh-trung-uong-dang-cong-san-dong-duong', 'nguyen-ai-quoc-tro-ve-nuoc', 'predecessor', 'predecessor', 1),
('hoi-nghi-lan-thu-8-ban-chap-hanh-trung-uong-dang-cong-san-dong-duong', 'thanh-lap-mat-tran-viet-nam-doc-lap-dong-minh-viet-minh', 'successor', 'successor', 1),
('hoi-nghi-pa-ri-ve-viet-nam', 'tong-tien-cong-va-noi-day-xuan-mau-than-1968', 'predecessor', 'predecessor', 1),
('hoi-nghi-pa-ri-ve-viet-nam', 'ki-ket-hiep-dinh-pa-ri-ve-cham-dut-chien-tranh-lap-lai-hoa-binh-o-viet-nam', 'successor', 'successor', 1),
('hoi-nghi-pa-ri-ve-viet-nam', 'thanh-lap-chinh-phu-cach-mang-lam-thoi-cong-hoa-mien-nam-viet-nam', 'successor', 'successor', 2),
('hoi-nghi-thanh-lap-dang-cong-san-viet-nam', 'su-ra-doi-cua-ba-to-chuc-cong-san-viet-nam', 'predecessor', 'predecessor', 1),
('hoi-nghi-thanh-lap-dang-cong-san-viet-nam', 'thanh-lap-mat-tran-dan-toc-thong-nhat-viet-nam-1930', 'successor', 'successor', 1),
('hoi-nghi-toan-quoc-cua-dang-cong-san-dong-duong-1945', 'uy-ban-khoi-nghia-ban-bo-quan-lenh-so-1', 'predecessor', 'predecessor', 1),
('hoi-nghi-toan-quoc-cua-dang-cong-san-dong-duong-1945', 'hoi-nghi-toan-quoc-cua-dang-tan-trao', 'related', 'same_topic', 1),
('hoi-nghi-toan-quoc-cua-dang-cong-san-dong-duong-1945', 'dai-hoi-quoc-dan-tan-trao', 'successor', 'successor', 1),
('hoi-nghi-toan-quoc-cua-dang-tan-trao', 'hoi-nghi-toan-quoc-cua-dang-cong-san-dong-duong-1945', 'related', 'same_topic', 1),
('hoi-the-dong-quan', 'khoi-nghia-lam-son', 'predecessor', 'predecessor', 1),
('hoi-the-dong-quan', 'nha-le-so-thanh-lap', 'successor', 'successor', 1),
('hoi-the-lung-nhai', 'nha-minh-thong-tri-huy-diet-van-minh-dai-viet', 'predecessor', 'predecessor', 1),
('hoi-the-lung-nhai', 'khoi-nghia-lam-son', 'successor', 'successor', 1),
('ke-hoach-na-va-1953', 'cac-chien-dich-tien-cong-quan-doi-viet-nam-1950-1953', 'predecessor', 'predecessor', 1),
('ke-hoach-na-va-1953', 'cuoc-tien-cong-chien-luoc-dong-xuan-1953-1954', 'successor', 'successor', 1),
('khang-chien-chong-quan-mong-co-1258', 'hoi-nghi-binh-than', 'successor', 'successor', 1),
('khang-chien-chong-quan-nguyen-1285', 'hoi-nghi-dien-hong', 'predecessor', 'predecessor', 1),
('khang-chien-chong-quan-nguyen-1285', 'khang-chien-chong-quan-nguyen-1287-1288', 'successor', 'successor', 1),
('khang-chien-chong-quan-nguyen-1287-1288', 'khang-chien-chong-quan-nguyen-1285', 'predecessor', 'predecessor', 1),
('khang-chien-chong-quan-thanh-1789', 'khang-chien-chong-quan-xiem-1784-1785', 'predecessor', 'predecessor', 1),
('khang-chien-chong-quan-tong-1075-1077', 'ly-thuong-kiet-tap-kich-kham-chau-liem-chau-ung-chau', 'related', 'related', 1),
('khang-chien-chong-quan-tong-981', 'dinh-tien-le-dong-do-hoa-lu', 'predecessor', 'predecessor', 1),
('khang-chien-chong-quan-trieu-an-duong-vuong', 'su-ra-doi-nha-nuoc-au-lac', 'predecessor', 'predecessor', 1),
('khang-chien-chong-quan-trieu-an-duong-vuong', 'khoi-nghia-hai-ba-trung', 'successor', 'successor', 1),
('khang-chien-chong-quan-xiem-1784-1785', 'phong-trao-tay-son-bung-no', 'predecessor', 'predecessor', 1),
('khang-chien-chong-quan-xiem-1784-1785', 'khang-chien-chong-quan-thanh-1789', 'successor', 'successor', 1),
('khang-chien-chong-thuc-dan-phap-trieu-nguyen', 'phap-tan-cong-da-nang-1858', 'related', 'related', 1),
('khang-chien-chong-thuc-dan-phap-trieu-nguyen', 'phong-trao-chong-thuc-dan-phap-xam-luoc-o-viet-nam', 'related', 'same_topic', 2),
('khang-chien-thang-loi', 'chien-dich-dien-bien-phu-1954', 'related', 'related', 1),
('khang-chien-thang-loi', 'ky-ket-hiep-dinh-go-ne-vo-1954', 'related', 'related', 2),
('khang-chien-toan-quoc-chong-thuc-dan-phap-bung-no', 'ki-tam-uoc-viet-phap', 'predecessor', 'predecessor', 1),
('khang-chien-toan-quoc-chong-thuc-dan-phap-bung-no', 'ho-chi-minh-ra-loi-keu-goi-toan-quoc-khang-chien', 'related', 'same_topic', 1),
('khang-chien-toan-quoc-chong-thuc-dan-phap-bung-no', 'chien-dau-cac-do-thi-phia-bac-vi-tuyen-16-1946-1947', 'successor', 'successor', 1),
('khoi-nghia-ba-trieu', 'khoi-nghia-hai-ba-trung', 'predecessor', 'predecessor', 1),
('khoi-nghia-ba-trieu', 'khoi-nghia-ly-bi-trieu-quang-phuc', 'successor', 'successor', 1),
('khoi-nghia-gianh-chinh-quyen-ha-noi', 'cac-tinh-gianh-chinh-quyen-som-nhat', 'predecessor', 'predecessor', 1),
('khoi-nghia-gianh-chinh-quyen-ha-noi', 'khoi-nghia-gianh-chinh-quyen-hue', 'successor', 'successor', 1),
('khoi-nghia-gianh-chinh-quyen-hue', 'khoi-nghia-gianh-chinh-quyen-ha-noi', 'predecessor', 'predecessor', 1),
('khoi-nghia-gianh-chinh-quyen-hue', 'khoi-nghia-gianh-chinh-quyen-sai-gon', 'successor', 'successor', 1),
('khoi-nghia-gianh-chinh-quyen-sai-gon', 'khoi-nghia-gianh-chinh-quyen-hue', 'predecessor', 'predecessor', 1),
('khoi-nghia-gianh-chinh-quyen-sai-gon', 'cac-dia-phuong-cuoi-cung-gianh-chinh-quyen', 'successor', 'successor', 1),
('khoi-nghia-hai-ba-trung', 'khang-chien-chong-quan-trieu-an-duong-vuong', 'predecessor', 'predecessor', 1),
('khoi-nghia-hai-ba-trung', 'khoi-nghia-ba-trieu', 'successor', 'successor', 1),
('khoi-nghia-khu-lien-lap-nuoc-lam-ap', 'hinh-thanh-phat-trien-van-minh-cham-pa', 'related', 'same_topic', 1),
('khoi-nghia-khuc-thua-du', 'khoi-nghia-phung-hung', 'predecessor', 'predecessor', 1),
('khoi-nghia-khuc-thua-du', 'ho-khuc-to-chuc-lai-lang-xa-the-ki-x', 'related', 'related', 1),
('khoi-nghia-khuc-thua-du', 'chien-thang-bach-dang-938', 'successor', 'successor', 1),
('khoi-nghia-lam-son', 'hoi-the-lung-nhai', 'predecessor', 'predecessor', 1),
('khoi-nghia-lam-son', 'hoi-the-dong-quan', 'successor', 'successor', 1),
('khoi-nghia-ly-bi-trieu-quang-phuc', 'khoi-nghia-ba-trieu', 'predecessor', 'predecessor', 1),
('khoi-nghia-ly-bi-trieu-quang-phuc', 'mai-thuc-loan-khoi-nghia', 'successor', 'successor', 1),
('khoi-nghia-mai-thuc-loan', 'mai-thuc-loan-khoi-nghia', 'related', 'same_topic', 1),
('khoi-nghia-phung-hung', 'mai-thuc-loan-khoi-nghia', 'predecessor', 'predecessor', 1),
('khoi-nghia-phung-hung', 'khoi-nghia-khuc-thua-du', 'successor', 'successor', 1),
('khung-hoang-cuoi-trieu-tran', 'cai-cach-ho-quy-ly-trieu-ho', 'successor', 'successor', 1),
('ki-ket-hiep-dinh-pa-ri-ve-cham-dut-chien-tranh-lap-lai-hoa-binh-o-viet-nam', 'hoi-nghi-pa-ri-ve-viet-nam', 'predecessor', 'predecessor', 1),
('ki-ket-hiep-dinh-pa-ri-ve-cham-dut-chien-tranh-lap-lai-hoa-binh-o-viet-nam', 'chien-tranh-pha-hoai-mien-bac-lan-thu-hai', 'predecessor', 'predecessor', 2),
('ki-ket-hiep-dinh-pa-ri-ve-cham-dut-chien-tranh-lap-lai-hoa-binh-o-viet-nam', 'hoi-nghi-ban-chap-hanh-trung-uong-dang-lan-thu-21', 'successor', 'successor', 1),
('ki-tam-uoc-viet-phap', 'ho-chi-minh-sang-phap-van-dong-ngoai-giao-va-ki-tam-uoc', 'predecessor', 'predecessor', 1),
('ki-tam-uoc-viet-phap', 'khang-chien-toan-quoc-chong-thuc-dan-phap-bung-no', 'successor', 'successor', 1),
('ki-tuyen-bo-ve-ung-xu-cua-cac-ben-o-bien-dong-doc', 'trung-quoc-danh-chiem-da-vanh-khan', 'related', 'same_topic', 1),
('ki-tuyen-bo-ve-ung-xu-cua-cac-ben-o-bien-dong-doc', 'viet-nam-thong-qua-luat-bien-viet-nam', 'related', 'same_topic', 2),
('ky-ket-hiep-dinh-go-ne-vo-1954', 'hoi-nghi-gio-ne-vo-ve-dong-duong', 'predecessor', 'predecessor', 1),
('ky-ket-hiep-dinh-go-ne-vo-1954', 'khang-chien-thang-loi', 'related', 'related', 1),
('ky-ket-hiep-dinh-go-ne-vo-1954', 'viet-nam-tam-thoi-bi-chia-cat-hai-mien', 'successor', 'successor', 1),
('lap-co-mat-vien', 'xoa-bo-gia-dinh-thanh-chia-thanh-12-tinh', 'predecessor', 'predecessor', 1),
('lap-co-mat-vien', 'thi-diem-chia-lai-ruong-dat-minh-mang', 'successor', 'successor', 1),
('lap-noi-cac-thay-the-van-thu-phong', 'doi-cac-doanh-quang-binh-quang-tri-quang-nam-thanh-tran', 'predecessor', 'predecessor', 1),
('lap-noi-cac-thay-the-van-thu-phong', 'xoa-bo-bac-thanh-chia-thanh-18-tinh', 'successor', 'successor', 1),
('le-nghi-dan-dat-luc-bo', 'le-thanh-tong-dua-luc-bo-thanh-co-quan-quyen-luc', 'successor', 'successor', 1),
('le-thanh-tong-dua-luc-bo-thanh-co-quan-quyen-luc', 'le-nghi-dan-dat-luc-bo', 'predecessor', 'predecessor', 1),
('le-thanh-tong-dua-luc-bo-thanh-co-quan-quyen-luc', 'cai-to-hanh-chinh-dia-phuong-12-thua-tuyen', 'successor', 'successor', 1),
('le-thanh-tong-dung-bia-tien-si-van-mieu', 'ban-hanh-quoc-trieu-hinh-luat', 'predecessor', 'predecessor', 1),
('lien-hop-quoc-vien-tro-viet-nam-1977-1986', 'viet-nam-thanh-vien-lien-hop-quoc', 'related', 'related', 1),
('ly-nhan-tong-lap-quoc-tu-giam', 'nha-ly-to-chuc-khoa-thi-nho-hoc-dau-tien', 'predecessor', 'predecessor', 1),
('ly-nhan-tong-lap-quoc-tu-giam', 'nha-ly-su-dung-thi-cu-nho-hoc', 'related', 'same_topic', 1),
('ly-thai-to-doi-do-thang-long', 'doi-do-ly-cong-uan', 'related', 'same_topic', 1),
('ly-thanh-tong-dung-van-mieu', 'doi-do-ly-cong-uan', 'predecessor', 'predecessor', 1),
('ly-thanh-tong-dung-van-mieu', 'nha-ly-xay-dung-van-mieu', 'related', 'same_topic', 1),
('ly-thanh-tong-dung-van-mieu', 'nha-ly-to-chuc-khoa-thi-nho-hoc-dau-tien', 'successor', 'successor', 1),
('ly-thuong-kiet-tap-kich-kham-chau-liem-chau-ung-chau', 'khang-chien-chong-quan-tong-1075-1077', 'related', 'related', 1),
('mai-thuc-loan-khoi-nghia', 'khoi-nghia-ly-bi-trieu-quang-phuc', 'predecessor', 'predecessor', 1),
('mai-thuc-loan-khoi-nghia', 'khoi-nghia-mai-thuc-loan', 'related', 'same_topic', 1),
('mai-thuc-loan-khoi-nghia', 'khoi-nghia-phung-hung', 'successor', 'successor', 1),
('minh-mang-len-ngoi-vua', 'doi-thi-thu-vien-thanh-van-thu-phong', 'successor', 'successor', 1),
('mit-tinh-chao-mung-uy-ban-quan-quan-sai-gon-1975', 'hoan-toan-giai-phong-mien-nam-viet-nam', 'predecessor', 'predecessor', 1),
('my-can-thiep-vao-dong-duong', 'my-thay-chan-phap-dung-chinh-quyen-ngo-dinh-diem', 'related', 'same_topic', 1),
('my-thay-chan-phap-dung-chinh-quyen-ngo-dinh-diem', 'viet-nam-tam-thoi-bi-chia-cat-hai-mien', 'predecessor', 'predecessor', 1),
('my-thay-chan-phap-dung-chinh-quyen-ngo-dinh-diem', 'my-can-thiep-vao-dong-duong', 'related', 'same_topic', 1),
('my-thay-chan-phap-dung-chinh-quyen-ngo-dinh-diem', 'hoi-nghi-ban-chap-hanh-trung-uong-lan-thu-15-dang-lao-dong-viet-nam', 'successor', 'successor', 1),
('ngo-quyen-xung-vuong-co-loa', 'chien-thang-bach-dang-938', 'predecessor', 'predecessor', 1),
('ngo-quyen-xung-vuong-co-loa', 'dinh-tien-le-dong-do-hoa-lu', 'successor', 'successor', 1),
('nguyen-ai-quoc-den-lien-xo-1923', 'nguyen-ai-quoc-hoat-dong-phap-1921-1923', 'predecessor', 'predecessor', 1),
('nguyen-ai-quoc-den-lien-xo-1923', 'nguyen-ai-quoc-den-quang-chau-1924', 'successor', 'successor', 1),
('nguyen-ai-quoc-den-quang-chau-1924', 'nguyen-ai-quoc-den-lien-xo-1923', 'predecessor', 'predecessor', 1),
('nguyen-ai-quoc-den-quang-chau-1924', 'ho-chi-minh-mo-lop-dao-tao-can-bo-tai-quang-chau-trung-quoc', 'related', 'related', 1),
('nguyen-ai-quoc-den-quang-chau-1924', 'thanh-lap-hoi-lien-hiep-cac-dan-toc-bi-ap-buc-a-dong-1925', 'related', 'related', 2),
('nguyen-ai-quoc-den-quang-chau-1924', 'nguyen-ai-quoc-thanh-lap-hoi-viet-nam-cach-mang-thanh-nien', 'successor', 'successor', 1),
('nguyen-ai-quoc-doc-luan-cuong-le-nin', 'nguyen-ai-quoc-gui-yeu-sach-vec-xai', 'predecessor', 'predecessor', 1),
('nguyen-ai-quoc-doc-luan-cuong-le-nin', 'nguyen-ai-quoc-gia-nhap-quoc-te-cong-san-va-sang-lap-dang-cong-san-phap', 'successor', 'successor', 1),
('nguyen-ai-quoc-gia-nhap-quoc-te-cong-san-va-sang-lap-dang-cong-san-phap', 'nguyen-ai-quoc-doc-luan-cuong-le-nin', 'predecessor', 'predecessor', 1),
('nguyen-ai-quoc-gia-nhap-quoc-te-cong-san-va-sang-lap-dang-cong-san-phap', 'nguyen-ai-quoc-hoat-dong-phap-1921-1923', 'successor', 'successor', 1),
('nguyen-ai-quoc-gui-yeu-sach-vec-xai', 'nguyen-tat-thanh-ra-di-tim-duong-cuu-nuoc', 'predecessor', 'predecessor', 1),
('nguyen-ai-quoc-gui-yeu-sach-vec-xai', 'nguyen-ai-quoc-doc-luan-cuong-le-nin', 'successor', 'successor', 1),
('nguyen-ai-quoc-hoat-dong-chau-au-siam-1927-1929', 'nguyen-ai-quoc-thanh-lap-hoi-viet-nam-cach-mang-thanh-nien', 'predecessor', 'predecessor', 1),
('nguyen-ai-quoc-hoat-dong-chau-au-siam-1927-1929', 'su-ra-doi-cua-ba-to-chuc-cong-san-viet-nam', 'successor', 'successor', 1),
('nguyen-ai-quoc-hoat-dong-lien-xo-1933', 'nguyen-ai-quoc-roi-lien-xo-tro-lai-trung-quoc', 'successor', 'successor', 1),
('nguyen-ai-quoc-hoat-dong-phap-1921-1923', 'nguyen-ai-quoc-gia-nhap-quoc-te-cong-san-va-sang-lap-dang-cong-san-phap', 'predecessor', 'predecessor', 1),
('nguyen-ai-quoc-hoat-dong-phap-1921-1923', 'nguyen-ai-quoc-thanh-lap-hoi-lien-hiep-thuoc-dia-1921', 'related', 'related', 1),
('nguyen-ai-quoc-hoat-dong-phap-1921-1923', 'nguyen-ai-quoc-den-lien-xo-1923', 'successor', 'successor', 1),
('nguyen-ai-quoc-roi-lien-xo-tro-lai-trung-quoc', 'nguyen-ai-quoc-hoat-dong-lien-xo-1933', 'predecessor', 'predecessor', 1),
('nguyen-ai-quoc-roi-lien-xo-tro-lai-trung-quoc', 'nguyen-ai-quoc-tro-ve-nuoc', 'successor', 'successor', 1),
('nguyen-ai-quoc-thanh-lap-hoi-lien-hiep-thuoc-dia-1921', 'nguyen-ai-quoc-hoat-dong-phap-1921-1923', 'related', 'related', 1),
('nguyen-ai-quoc-thanh-lap-hoi-lien-hiep-thuoc-dia-1921', 'nguyen-ai-quoc-thanh-lap-hoi-lien-hiep-thuoc-dia-va-bao-le-paria', 'related', 'same_topic', 2),
('nguyen-ai-quoc-thanh-lap-hoi-lien-hiep-thuoc-dia-va-bao-le-paria', 'nguyen-ai-quoc-thanh-lap-hoi-lien-hiep-thuoc-dia-1921', 'related', 'same_topic', 1),
('nguyen-ai-quoc-thanh-lap-hoi-viet-nam-cach-mang-thanh-nien', 'nguyen-ai-quoc-den-quang-chau-1924', 'predecessor', 'predecessor', 1),
('nguyen-ai-quoc-thanh-lap-hoi-viet-nam-cach-mang-thanh-nien', 'nguyen-ai-quoc-hoat-dong-chau-au-siam-1927-1929', 'successor', 'successor', 1),
('nguyen-ai-quoc-tro-ve-nuoc', 'nguyen-ai-quoc-roi-lien-xo-tro-lai-trung-quoc', 'predecessor', 'predecessor', 1),
('nguyen-ai-quoc-tro-ve-nuoc', 'hoi-nghi-lan-thu-8-ban-chap-hanh-trung-uong-dang-cong-san-dong-duong', 'successor', 'successor', 1),
('nguyen-hue-dung-chan-chieu-mo-binh-si', 'phong-trao-tay-son-bung-no', 'related', 'related', 1),
('nguyen-tat-thanh-ra-di-tim-duong-cuu-nuoc', 'nguyen-tat-thanh-roi-phan-thiet-vao-sai-gon', 'predecessor', 'predecessor', 1),
('nguyen-tat-thanh-ra-di-tim-duong-cuu-nuoc', 'nguyen-ai-quoc-gui-yeu-sach-vec-xai', 'successor', 'successor', 1),
('nguyen-tat-thanh-roi-phan-thiet-vao-sai-gon', 'nguyen-tat-thanh-tham-gia-chong-thue-hue', 'predecessor', 'predecessor', 1),
('nguyen-tat-thanh-roi-phan-thiet-vao-sai-gon', 'nguyen-tat-thanh-ra-di-tim-duong-cuu-nuoc', 'successor', 'successor', 1),
('nguyen-tat-thanh-tham-gia-chong-thue-hue', 'nguyen-tat-thanh-roi-phan-thiet-vao-sai-gon', 'successor', 'successor', 1),
('nha-le-so-thanh-lap', 'hoi-the-dong-quan', 'predecessor', 'predecessor', 1),
('nha-ly-su-dung-thi-cu-nho-hoc', 'ly-nhan-tong-lap-quoc-tu-giam', 'related', 'same_topic', 1),
('nha-ly-su-dung-thi-cu-nho-hoc', 'nha-ly-to-chuc-khoa-thi-nho-hoc-dau-tien', 'related', 'same_topic', 2),
('nha-ly-to-chuc-khoa-thi-nho-hoc-dau-tien', 'ly-thanh-tong-dung-van-mieu', 'predecessor', 'predecessor', 1),
('nha-ly-to-chuc-khoa-thi-nho-hoc-dau-tien', 'nha-ly-su-dung-thi-cu-nho-hoc', 'related', 'same_topic', 1),
('nha-ly-to-chuc-khoa-thi-nho-hoc-dau-tien', 'nha-ly-xay-dung-van-mieu', 'related', 'same_topic', 2),
('nha-ly-to-chuc-khoa-thi-nho-hoc-dau-tien', 'ly-nhan-tong-lap-quoc-tu-giam', 'successor', 'successor', 1),
('nha-ly-xay-dung-van-mieu', 'ly-thanh-tong-dung-van-mieu', 'related', 'same_topic', 1),
('nha-ly-xay-dung-van-mieu', 'nha-ly-to-chuc-khoa-thi-nho-hoc-dau-tien', 'related', 'same_topic', 2),
('nha-minh-thong-tri-huy-diet-van-minh-dai-viet', 'nha-minh-xam-luoc-dai-ngu', 'predecessor', 'predecessor', 1),
('nha-minh-thong-tri-huy-diet-van-minh-dai-viet', 'hoi-the-lung-nhai', 'successor', 'successor', 1),
('nha-minh-xam-luoc-dai-ngu', 'cai-cach-ho-quy-ly-trieu-ho', 'predecessor', 'predecessor', 1),
('nha-minh-xam-luoc-dai-ngu', 'nha-minh-thong-tri-huy-diet-van-minh-dai-viet', 'successor', 'successor', 1),
('nhat-ban-tuyen-bo-dau-hang-dong-minh', 'cao-trao-khang-nhat-cuu-nuoc', 'predecessor', 'predecessor', 1),
('nhat-ban-tuyen-bo-dau-hang-dong-minh', 'uy-ban-khoi-nghia-ban-bo-quan-lenh-so-1', 'successor', 'successor', 1),
('phan-boi-chau-sang-nhat-ban-1905', 'hoat-dong-doi-ngoai-phan-boi-chau', 'related', 'same_topic', 1),
('phan-boi-chau-sang-nhat-ban-1905', 'phong-trao-dong-du', 'related', 'same_topic', 2),
('phan-boi-chau-sang-nhat-ban-1905', 'phan-boi-chau-ve-trung-quoc-1911', 'related', 'same_topic', 3),
('phan-boi-chau-ve-trung-quoc-1911', 'thanh-lap-lien-minh-dong-a-1908', 'predecessor', 'predecessor', 1),
('phan-boi-chau-ve-trung-quoc-1911', 'phan-boi-chau-sang-nhat-ban-1905', 'related', 'same_topic', 1),
('phan-boi-chau-ve-trung-quoc-1911', 'thanh-lap-viet-nam-quang-phuc-hoi-1912', 'successor', 'successor', 1),
('phan-chau-trinh-sang-phap-1911', 'hoat-dong-doi-ngoai-phan-chau-trinh', 'related', 'same_topic', 1),
('phap-chiem-bac-ki-lan-1', 'phap-chiem-sau-tinh-nam-ki', 'predecessor', 'predecessor', 1),
('phap-chiem-bac-ki-lan-1', 'phap-chiem-bac-ki-lan-2', 'successor', 'successor', 1),
('phap-chiem-bac-ki-lan-2', 'phap-chiem-bac-ki-lan-1', 'predecessor', 'predecessor', 1),
('phap-chiem-bac-ki-lan-2', 'hiep-uoc-hac-mang', 'successor', 'successor', 1),
('phap-chiem-sau-tinh-nam-ki', 'phap-tan-cong-da-nang-1858', 'predecessor', 'predecessor', 1),
('phap-chiem-sau-tinh-nam-ki', 'phap-chiem-bac-ki-lan-1', 'successor', 'successor', 1),
('phap-danh-up-uy-ban-hanh-chinh-nam-bo-1945', 'phap-xa-sung-sai-gon-cho-lon-1945', 'predecessor', 'predecessor', 1),
('phap-danh-up-uy-ban-hanh-chinh-nam-bo-1945', 'thanh-lap-uy-ban-khang-chien-nam-bo-1945', 'successor', 'successor', 1),
('phap-gui-cong-ham-phan-doi-nhat-ban-kiem-soat-truong-sa', 'phap-xay-dung-bia-chu-quyen-hoang-sa', 'predecessor', 'predecessor', 1),
('phap-tan-cong-da-nang-1858', 'khang-chien-chong-thuc-dan-phap-trieu-nguyen', 'related', 'related', 1),
('phap-tan-cong-da-nang-1858', 'thuc-dan-phap-no-sung-tan-cong-da-nang', 'related', 'same_topic', 2),
('phap-tan-cong-da-nang-1858', 'phap-chiem-sau-tinh-nam-ki', 'successor', 'successor', 1),
('phap-xa-sung-sai-gon-cho-lon-1945', 'phap-danh-up-uy-ban-hanh-chinh-nam-bo-1945', 'successor', 'successor', 1),
('phap-xay-dung-bia-chu-quyen-hoang-sa', 'phap-xay-dung-cot-hai-dang-hoang-sa', 'predecessor', 'predecessor', 1),
('phap-xay-dung-bia-chu-quyen-hoang-sa', 'phap-gui-cong-ham-phan-doi-nhat-ban-kiem-soat-truong-sa', 'successor', 'successor', 1),
('phap-xay-dung-cot-hai-dang-hoang-sa', 'phap-xay-dung-bia-chu-quyen-hoang-sa', 'successor', 'successor', 1),
('phat-hanh-tien-giay-thong-bao-hoi-sao', 'cai-cach-ho-quy-ly-trieu-ho', 'related', 'same_topic', 1),
('phat-hanh-tien-giay-thong-bao-hoi-sao', 'ban-hanh-chinh-sach-han-dien', 'related', 'same_topic', 2),
('philippin-chiem-dong-9-dao-truong-sa', 'philippin-tuyen-bo-quyen-khai-thac-lap-nghiep-truong-sa', 'related', 'same_topic', 1),
('philippin-chiem-dong-9-dao-truong-sa', 'quan-doi-sai-gon-that-bai-bao-ve-hoang-sa', 'related', 'same_topic', 2),
('philippin-tuyen-bo-quyen-khai-thac-lap-nghiep-truong-sa', 'philippin-chiem-dong-9-dao-truong-sa', 'related', 'same_topic', 1),
('philippin-tuyen-bo-quyen-khai-thac-lap-nghiep-truong-sa', 'viet-nam-danh-chiem-nua-phia-dong-hoang-sa', 'related', 'same_topic', 2),
('phong-trao-can-vuong', 'hiep-uoc-pa-to-not', 'predecessor', 'predecessor', 1),
('phong-trao-chong-thuc-dan-phap-xam-luoc-o-viet-nam', 'khang-chien-chong-thuc-dan-phap-trieu-nguyen', 'related', 'same_topic', 1),
('phong-trao-dong-du', 'hoat-dong-doi-ngoai-phan-boi-chau', 'related', 'same_topic', 1),
('phong-trao-dong-du', 'phan-boi-chau-sang-nhat-ban-1905', 'related', 'same_topic', 2),
('phong-trao-dong-du', 'thanh-lap-lien-minh-dong-a-1908', 'successor', 'successor', 1),
('phong-trao-dong-khoi', 'hoi-nghi-ban-chap-hanh-trung-uong-lan-thu-15-dang-lao-dong-viet-nam', 'predecessor', 'predecessor', 1),
('phong-trao-dong-khoi', 'thanh-lap-mat-tran-dan-toc-giai-phong-mien-nam-viet-nam', 'successor', 'successor', 1),
('phong-trao-tay-son-bung-no', 'nguyen-hue-dung-chan-chieu-mo-binh-si', 'related', 'related', 1),
('phong-trao-tay-son-bung-no', 'khang-chien-chong-quan-xiem-1784-1785', 'successor', 'successor', 1),
('phu-nam-tro-thanh-vuong-quoc-hung-manh', 'hinh-thanh-phat-trien-van-minh-phu-nam', 'related', 'same_topic', 1),
('quan-doi-sai-gon-that-bai-bao-ve-hoang-sa', 'philippin-chiem-dong-9-dao-truong-sa', 'related', 'same_topic', 1),
('quan-doi-sai-gon-that-bai-bao-ve-hoang-sa', 'quan-giai-phong-mien-nam-viet-nam-tiep-quan-truong-sa', 'related', 'same_topic', 2),
('quan-doi-sai-gon-that-bai-bao-ve-hoang-sa', 'trung-quoc-danh-chiem-toan-bo-hoang-sa', 'related', 'same_topic', 3),
('quan-giai-phong-mien-nam-viet-nam-tiep-quan-truong-sa', 'quan-doi-sai-gon-that-bai-bao-ve-hoang-sa', 'related', 'same_topic', 1),
('quan-he-viet-nam-my-doi-tac-chien-luoc-toan-dien', 'viet-nam-binh-thuong-hoa-quan-he-my', 'predecessor', 'predecessor', 1),
('quan-li-hanh-chinh-chinh-quyen-sai-gon-hoang-sa-truong-sa', 'viet-nam-danh-chiem-nua-phia-dong-hoang-sa', 'related', 'same_topic', 1),
('quoc-hoi-khoa-vi-doi-ten-sai-gon-thanh-thanh-pho-ho-chi-minh', 'thuc-hien-thong-nhat-dat-nuoc-viet-nam', 'predecessor', 'predecessor', 1),
('su-ra-doi-cua-ba-to-chuc-cong-san-viet-nam', 'nguyen-ai-quoc-hoat-dong-chau-au-siam-1927-1929', 'predecessor', 'predecessor', 1),
('su-ra-doi-cua-ba-to-chuc-cong-san-viet-nam', 'hoi-nghi-thanh-lap-dang-cong-san-viet-nam', 'successor', 'successor', 1),
('su-ra-doi-nha-nuoc-au-lac', 'su-ra-doi-nha-nuoc-van-lang', 'predecessor', 'predecessor', 1),
('su-ra-doi-nha-nuoc-au-lac', 'khang-chien-chong-quan-trieu-an-duong-vuong', 'successor', 'successor', 1),
('su-ra-doi-nha-nuoc-van-lang', 'su-ra-doi-nha-nuoc-au-lac', 'successor', 'successor', 1),
('thanh-lap-chinh-phu-cach-mang-lam-thoi-cong-hoa-mien-nam-viet-nam', 'hoi-nghi-pa-ri-ve-viet-nam', 'predecessor', 'predecessor', 1),
('thanh-lap-chinh-phu-cach-mang-lam-thoi-cong-hoa-mien-nam-viet-nam', 'cuoc-tien-cong-chien-luoc-nam-1972', 'successor', 'successor', 1),
('thanh-lap-hoi-lien-hiep-cac-dan-toc-bi-ap-buc-a-dong-1925', 'nguyen-ai-quoc-den-quang-chau-1924', 'related', 'related', 1),
('thanh-lap-huyen-hoang-sa-va-huyen-truong-sa', 'trung-quoc-danh-chiem-dao-gac-ma-len-dao-chu-thap-va-mot-so-dao-khac-truong-sa', 'related', 'same_topic', 1),
('thanh-lap-huyen-hoang-sa-va-huyen-truong-sa', 'viet-nam-ban-hanh-tuyen-bo-vung-bien-them-luc-dia', 'related', 'same_topic', 2),
('thanh-lap-lien-minh-dong-a-1908', 'phong-trao-dong-du', 'predecessor', 'predecessor', 1),
('thanh-lap-lien-minh-dong-a-1908', 'phan-boi-chau-ve-trung-quoc-1911', 'successor', 'successor', 1),
('thanh-lap-mat-tran-dan-toc-giai-phong-mien-nam-viet-nam', 'phong-trao-dong-khoi', 'predecessor', 'predecessor', 1),
('thanh-lap-mat-tran-dan-toc-giai-phong-mien-nam-viet-nam', 'thanh-lap-quan-giai-phong-mien-nam', 'successor', 'successor', 1),
('thanh-lap-mat-tran-dan-toc-thong-nhat-viet-nam-1930', 'hoi-nghi-thanh-lap-dang-cong-san-viet-nam', 'predecessor', 'predecessor', 1),
('thanh-lap-mat-tran-dan-toc-thong-nhat-viet-nam-1930', 'thanh-lap-mat-tran-viet-nam-doc-lap-dong-minh-viet-minh', 'successor', 'successor', 1),
('thanh-lap-mat-tran-viet-nam-doc-lap-dong-minh-viet-minh', 'hoi-nghi-lan-thu-8-ban-chap-hanh-trung-uong-dang-cong-san-dong-duong', 'predecessor', 'predecessor', 1),
('thanh-lap-mat-tran-viet-nam-doc-lap-dong-minh-viet-minh', 'thanh-lap-mat-tran-dan-toc-thong-nhat-viet-nam-1930', 'predecessor', 'predecessor', 2),
('thanh-lap-mat-tran-viet-nam-doc-lap-dong-minh-viet-minh', 'thanh-lap-tieu-doi-du-kich-thoat-li-dau-tien-o-cao-bang', 'successor', 'successor', 1),
('thanh-lap-mat-tran-viet-nam-doc-lap-dong-minh-viet-minh', 'cach-mang-thang-tam-nam-1945', 'successor', 'successor', 2),
('thanh-lap-quan-giai-phong-mien-nam', 'thanh-lap-mat-tran-dan-toc-giai-phong-mien-nam-viet-nam', 'predecessor', 'predecessor', 1),
('thanh-lap-quan-giai-phong-mien-nam', 'chien-thang-ap-bac', 'successor', 'successor', 1),
('thanh-lap-tieu-doi-du-kich-thoat-li-dau-tien-o-cao-bang', 'thanh-lap-mat-tran-viet-nam-doc-lap-dong-minh-viet-minh', 'predecessor', 'predecessor', 1),
('thanh-lap-tieu-doi-du-kich-thoat-li-dau-tien-o-cao-bang', 'ho-chi-minh-di-trung-quoc-phoi-hop-chong-nhat', 'successor', 'successor', 1),
('thanh-lap-uy-ban-khang-chien-nam-bo-1945', 'phap-danh-up-uy-ban-hanh-chinh-nam-bo-1945', 'predecessor', 'predecessor', 1),
('thanh-lap-va-hoat-dong-doi-dan-binh-hoang-sa-bac-hai', 'do-dac-cam-moc-chu-quyen-hoang-sa-pham-huu-nhat', 'successor', 'successor', 1),
('thanh-lap-viet-nam-quang-phuc-hoi-1912', 'phan-boi-chau-ve-trung-quoc-1911', 'predecessor', 'predecessor', 1),
('thi-diem-chia-lai-ruong-dat-minh-mang', 'lap-co-mat-vien', 'predecessor', 'predecessor', 1),
('thoi-gia-long-tri-vi', 'trieu-nguyen-thanh-lap', 'related', 'same_topic', 1),
('thuc-dan-phap-no-sung-tan-cong-da-nang', 'phap-tan-cong-da-nang-1858', 'related', 'same_topic', 1),
('thuc-hien-thong-nhat-dat-nuoc-viet-nam', 'hoan-toan-giai-phong-mien-nam-viet-nam', 'predecessor', 'predecessor', 1),
('thuc-hien-thong-nhat-dat-nuoc-viet-nam', 'quoc-hoi-khoa-vi-doi-ten-sai-gon-thanh-thanh-pho-ho-chi-minh', 'successor', 'successor', 1),
('tong-khoi-nghia-gianh-chinh-quyen', 'cac-dia-phuong-cuoi-cung-gianh-chinh-quyen', 'predecessor', 'predecessor', 1),
('tong-khoi-nghia-gianh-chinh-quyen', 'giai-phong-thi-xa-thai-nguyen', 'related', 'related', 1),
('tong-khoi-nghia-gianh-chinh-quyen', 'ho-chi-minh-cong-bo-tuyen-ngon-doc-lap', 'successor', 'successor', 1),
('tong-tien-cong-va-noi-day-xuan-mau-than-1968', 'chien-thang-van-tuong', 'predecessor', 'predecessor', 1),
('tong-tien-cong-va-noi-day-xuan-mau-than-1968', 'hoi-nghi-pa-ri-ve-viet-nam', 'successor', 'successor', 1),
('trieu-nguyen-thanh-lap', 'thoi-gia-long-tri-vi', 'related', 'same_topic', 1),
('trung-quoc-danh-chiem-da-vanh-khan', 'chien-si-hai-quan-nhan-dan-viet-nam-hi-sinh-bao-ve-gac-ma-co-lin-len-dao', 'related', 'same_topic', 1),
('trung-quoc-danh-chiem-da-vanh-khan', 'ki-tuyen-bo-ve-ung-xu-cua-cac-ben-o-bien-dong-doc', 'related', 'same_topic', 2),
('trung-quoc-danh-chiem-dao-gac-ma-len-dao-chu-thap-va-mot-so-dao-khac-truong-sa', 'chien-si-hai-quan-nhan-dan-viet-nam-hi-sinh-bao-ve-gac-ma-co-lin-len-dao', 'related', 'same_topic', 1),
('trung-quoc-danh-chiem-dao-gac-ma-len-dao-chu-thap-va-mot-so-dao-khac-truong-sa', 'thanh-lap-huyen-hoang-sa-va-huyen-truong-sa', 'related', 'same_topic', 2),
('trung-quoc-danh-chiem-toan-bo-hoang-sa', 'quan-doi-sai-gon-that-bai-bao-ve-hoang-sa', 'related', 'same_topic', 1),
('uy-ban-khoi-nghia-ban-bo-quan-lenh-so-1', 'nhat-ban-tuyen-bo-dau-hang-dong-minh', 'predecessor', 'predecessor', 1),
('uy-ban-khoi-nghia-ban-bo-quan-lenh-so-1', 'hoi-nghi-toan-quoc-cua-dang-cong-san-dong-duong-1945', 'successor', 'successor', 1),
('viet-nam-ban-hanh-tuyen-bo-vung-bien-them-luc-dia', 'thanh-lap-huyen-hoang-sa-va-huyen-truong-sa', 'related', 'same_topic', 1),
('viet-nam-binh-thuong-hoa-quan-he-my', 'xay-dung-va-dong-dien-duong-day-500kv-bac-nam-mach-1', 'predecessor', 'predecessor', 1),
('viet-nam-binh-thuong-hoa-quan-he-my', 'viet-nam-binh-thuong-hoa-quan-he-trung-quoc', 'related', 'same_topic', 1),
('viet-nam-binh-thuong-hoa-quan-he-my', 'quan-he-viet-nam-my-doi-tac-chien-luoc-toan-dien', 'successor', 'successor', 1),
('viet-nam-binh-thuong-hoa-quan-he-my', 'viet-nam-gia-nhap-asean', 'successor', 'successor', 2),
('viet-nam-binh-thuong-hoa-quan-he-trung-quoc', 'dai-hoi-dai-bieu-toan-quoc-lan-thu-vii-cua-dang-cong-san-viet-nam', 'predecessor', 'predecessor', 1),
('viet-nam-binh-thuong-hoa-quan-he-trung-quoc', 'viet-nam-binh-thuong-hoa-quan-he-my', 'related', 'same_topic', 1),
('viet-nam-binh-thuong-hoa-quan-he-trung-quoc', 'xay-dung-va-dong-dien-duong-day-500kv-bac-nam-mach-1', 'successor', 'successor', 1),
('viet-nam-danh-chiem-nua-phia-dong-hoang-sa', 'philippin-tuyen-bo-quyen-khai-thac-lap-nghiep-truong-sa', 'related', 'same_topic', 1),
('viet-nam-danh-chiem-nua-phia-dong-hoang-sa', 'quan-li-hanh-chinh-chinh-quyen-sai-gon-hoang-sa-truong-sa', 'related', 'same_topic', 2),
('viet-nam-gia-nhap-asean', 'viet-nam-binh-thuong-hoa-quan-he-my', 'predecessor', 'predecessor', 1),
('viet-nam-gia-nhap-asean', 'viet-nam-tham-gia-afta', 'related', 'same_topic', 1),
('viet-nam-gia-nhap-asean', 'dai-hoi-dai-bieu-toan-quoc-lan-thu-viii-cua-dang-cong-san-viet-nam', 'successor', 'successor', 1),
('viet-nam-ki-ket-evfta', 'viet-nam-ki-ket-rcep', 'related', 'same_topic', 1),
('viet-nam-ki-ket-evfta', 'viet-nam-tham-gia-afta', 'related', 'same_topic', 2),
('viet-nam-ki-ket-rcep', 'viet-nam-ki-ket-evfta', 'related', 'same_topic', 1),
('viet-nam-tam-thoi-bi-chia-cat-hai-mien', 'ky-ket-hiep-dinh-go-ne-vo-1954', 'predecessor', 'predecessor', 1),
('viet-nam-tam-thoi-bi-chia-cat-hai-mien', 'my-thay-chan-phap-dung-chinh-quyen-ngo-dinh-diem', 'successor', 'successor', 1),
('viet-nam-tham-gia-afta', 'viet-nam-gia-nhap-asean', 'related', 'same_topic', 1),
('viet-nam-tham-gia-afta', 'viet-nam-ki-ket-evfta', 'related', 'same_topic', 2),
('viet-nam-thanh-vien-lien-hop-quoc', 'lien-hop-quoc-vien-tro-viet-nam-1977-1986', 'related', 'related', 1),
('viet-nam-thong-qua-luat-bien-viet-nam', 'ban-hanh-nghi-quyet-36-nq-tw-ve-chien-luoc-phat-trien-kinh-te-bien', 'related', 'same_topic', 1),
('viet-nam-thong-qua-luat-bien-viet-nam', 'ki-tuyen-bo-ve-ung-xu-cua-cac-ben-o-bien-dong-doc', 'related', 'same_topic', 2),
('xay-dung-va-dong-dien-duong-day-500kv-bac-nam-mach-1', 'viet-nam-binh-thuong-hoa-quan-he-trung-quoc', 'predecessor', 'predecessor', 1),
('xay-dung-va-dong-dien-duong-day-500kv-bac-nam-mach-1', 'viet-nam-binh-thuong-hoa-quan-he-my', 'successor', 'successor', 1),
('xoa-bo-bac-thanh-chia-thanh-18-tinh', 'bac-thanh-duoc-lap', 'predecessor', 'predecessor', 1),
('xoa-bo-bac-thanh-chia-thanh-18-tinh', 'lap-noi-cac-thay-the-van-thu-phong', 'predecessor', 'predecessor', 2),
('xoa-bo-bac-thanh-chia-thanh-18-tinh', 'xoa-bo-gia-dinh-thanh-chia-thanh-12-tinh', 'successor', 'successor', 1),
('xoa-bo-gia-dinh-thanh-chia-thanh-12-tinh', 'gia-dinh-thanh-duoc-lap', 'predecessor', 'predecessor', 1),
('xoa-bo-gia-dinh-thanh-chia-thanh-12-tinh', 'xoa-bo-bac-thanh-chia-thanh-18-tinh', 'predecessor', 'predecessor', 2),
('xoa-bo-gia-dinh-thanh-chia-thanh-12-tinh', 'lap-co-mat-vien', 'successor', 'successor', 1);

INSERT INTO event_relations
    (source_event_id, target_event_id, association_type, relation_type, sort_order)
SELECT seed.source_event_id,
       seed.target_event_id,
       seed.association_type,
       seed.relation_type,
       seed.sort_order
FROM event_relation_seed seed
JOIN historical_events source_event
    ON source_event.id COLLATE utf8mb4_unicode_ci = seed.source_event_id COLLATE utf8mb4_unicode_ci
JOIN historical_events target_event
    ON target_event.id COLLATE utf8mb4_unicode_ci = seed.target_event_id COLLATE utf8mb4_unicode_ci
ON DUPLICATE KEY UPDATE
    association_type = VALUES(association_type),
    relation_type = VALUES(relation_type),
    sort_order = VALUES(sort_order);

DROP TEMPORARY TABLE event_relation_seed;

COMMIT;

START TRANSACTION;

UPDATE historical_events he
LEFT JOIN (
    SELECT source_event_id, JSON_ARRAYAGG(target_event_id) AS ids
    FROM (
        SELECT source_event_id, target_event_id, MIN(sort_order) AS sort_order
        FROM event_relations
        WHERE association_type = 'predecessor'
        GROUP BY source_event_id, target_event_id
    ) x
    GROUP BY source_event_id
) pred ON pred.source_event_id = he.id
LEFT JOIN (
    SELECT source_event_id, JSON_ARRAYAGG(target_event_id) AS ids
    FROM (
        SELECT source_event_id, target_event_id, MIN(sort_order) AS sort_order
        FROM event_relations
        WHERE association_type = 'successor'
        GROUP BY source_event_id, target_event_id
    ) x
    GROUP BY source_event_id
) succ ON succ.source_event_id = he.id
LEFT JOIN (
    SELECT source_event_id, JSON_ARRAYAGG(target_event_id) AS ids
    FROM (
        SELECT er.source_event_id, er.target_event_id, MIN(er.sort_order) AS sort_order
        FROM event_relations er
        WHERE er.association_type = 'related'
          AND NOT EXISTS (
              SELECT 1
              FROM event_relations temporal
              WHERE temporal.source_event_id = er.source_event_id
                AND temporal.target_event_id = er.target_event_id
                AND temporal.association_type IN ('predecessor', 'successor')
          )
        GROUP BY er.source_event_id, er.target_event_id
    ) x
    GROUP BY source_event_id
) rel ON rel.source_event_id = he.id
SET he.raw_json = JSON_SET(
    he.raw_json,
    '$.associations.predecessorEventIds', COALESCE(pred.ids, JSON_ARRAY()),
    '$.associations.successorEventIds', COALESCE(succ.ids, JSON_ARRAY()),
    '$.associations.relatedEventIds', COALESCE(rel.ids, JSON_ARRAY()),
    '$.associations.relatedFigureIds', COALESCE(JSON_EXTRACT(he.raw_json, '$.associations.relatedFigureIds'), JSON_ARRAY())
);

COMMIT;
