ALTER TABLE users
    MODIFY COLUMN updated_at DATETIME(6) NOT NULL
        DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),
    ADD COLUMN auth_version BIGINT NOT NULL DEFAULT 0;
